services:
  engine:
    build:
      context: ./zeno-engine-python
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./zeno-engine-python:/app
    command: ["python", "src/zenoengine/main.py", "--scene", "RTI_2D", "--steps", "500", "--dim", "2"]
    ports:
      - "9000:9000"  # Still useful if API is ever used
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  viewer:
    build:
      context: ./zeno-gui
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./zeno-gui:/app
      - /app/node_modules
    # command: ["yarn", "dev", "--host"]
    ports:
      - "3000:3000"
    restart: unless-stopped
