services:
  engine:
    build:
      context: ./zeno-engine-python
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./zeno-engine-python:/app
    # command: ["python", "entry.py", "--scene", "RTI_2D"]
    ports:
      - "9000:9000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  viewer:
    build:
      context: ./zeno-viewer
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./zeno-viewer:/app
      - /app/node_modules
    # command: ["yarn", "dev", "--host"]
    ports:
      - "3000:3000"
    restart: unless-stopped
