services:
  engine:
    build:
      context: ./zeno-engine-python
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./zeno-engine-python/outputs:/app/outputs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  viewer:
    build:
      context: ./zeno-gui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
