FROM python:3.13.5

# System deps
RUN apt-get update && apt-get install -y gcc && \
    pip install --upgrade pip pipenv

WORKDIR /app

# Leverage caching for dependencies
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy --dev

# Now bring in the rest
COPY . .

EXPOSE 9000

# Start dev server (with hot-reload)
CMD ["uvicorn", "zenoengine.api.main:app", "--host", "0.0.0.0", "--port", "9000", "--reload"]
