FROM python:3.13.5

RUN apt-get update && apt-get install -y gcc && \
    pip install --upgrade pip pipenv

WORKDIR /app

COPY zeno-engine-python/Pipfile zeno-engine-python/Pipfile.lock ./
RUN pipenv install

COPY zeno-engine-python /app

CMD ["bash"]
